### ISSUE TITLE
Update to pull selenium server 4.18

### ISSUE THREAD

**Issue by AutomatedTester** [beatfactor/selenium-server-jar-download#4]
We need to update https://github.com/nightwatchjs/selenium-server-jar-download/blob/main/package.json#L8 to match the latest selenium server, 4.18 at time of raising this.

**Comment by matte23n** [comment]
I can take care of this, just need to update the version in the package json and do some tests for everything to continue working correctly, or to eventually adapt some code if is not working

**Comment by AutomatedTester** [comment]
Hopefully you won't have to do much more than update the `package.json`. If it does break please update so I can help

**Comment by urizennnn** [comment]
hi @AutomatedTester  I have fixed this locally but can't seem to push the code to  a new branch for a PR review. any suggestions?

**Comment by urizennnn** [comment]
@AutomatedTester please review my pr as i think i have fixed this issue

**Comment by maha-sachin** [comment]
Hi @AutomatedTester, I am Maha. can you help me to assign the first issue? I'm eager to contribute to the project.
